services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    networks:
      - todo-prod

networks:
  todo-prod: